Repository badgateway/react-ketting, pull requests merged in 2020-10, with the labels that each got.

#12 feat: adding RequiredLogin component
  package-lock.json
  package.json
  src/components/RequireLogin.tsx
  src/index.tsx
Labels: enhancement

#13 Resource lifecycle bug.
  src/resource-lifecycle.ts
Labels: bug

#14 Release 1.1
  changelog.md
  package-lock.json
  package.json
Labels: dependencies

#15 useCollection hook
  src/hooks/use-collection.ts
  src/hooks/use-resource.ts
  src/index.tsx
Labels: enhancement

#18 Preparing 1.2 release
  changelog.md
  package-lock.json
  package.json
Labels: dependencies, enhancement
