Repository badgateway/react-ketting, pull requests merged in 2021-03, with the labels that each got.

#35 Add 'refreshOnStale' option to useResource hook
  changelog.md
  src/hooks/use-resource.ts
Labels: enhancement

#36 Preparing for 1.4.3 release
  .eslintrc.json
  .github/CODE_OF_CONDUCT.md
  .github/workflows/test.yml
  .travis.yml
  Makefile
  package-lock.json
  package.json
  tsconfig.json
Labels: enhancement

#37 exporting useResolveResource
  changelog.md
  src/index.tsx
Labels: enhancement

#38 Ketting 7 support
  changelog.md
  package-lock.json
  package.json
  src/hooks/use-resource.ts
Labels: enhancement

#39 Correctly handle expired OAuth2 refresh tokens
  .github/workflows/test.yml
  changelog.md
  src/components/RequireLogin.tsx
Labels: bug

#40 Handle expired refresh 2.x
  .github/workflows/test.yml
  changelog.md
  src/components/RequireLogin.tsx
Labels: bug

#41 Export UseResourceOptions
  src/hooks/use-resource.ts
  src/index.tsx
Labels: enhancement

#42 releasing v2 beta 0
  changelog.md
  package-lock.json
  package.json
Labels: enhancement

#45 Remove 'browser' from package.json
  package.json
Labels: bug

#46 Release 1.4.6
  changelog.md
  package-lock.json
  package.json
Labels: dependencies
